project_id = "oabdnwrjpilpfrrjnlkp"

[functions.analyze-documents]
verify_jwt = false

[functions.generate-email]
verify_jwt = false

[functions.extract-negative-points]
verify_jwt = false

[functions.extract-company-name]
verify_jwt = false

[functions.detect-document-type]
verify_jwt = false
